/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNewStud: typeof import('./src/components/addNewStud.vue')['default']
    AddStudBtn: typeof import('./src/components/addStudBtn.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    Drawer: typeof import('./src/components/drawer.vue')['default']
    DrawerForm: typeof import('./src/components/drawerForm.vue')['default']
    EditInfo: typeof import('./src/components/editInfo.vue')['default']
    EditStudInfo: typeof import('./src/components/editStudInfo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Login: typeof import('./src/components/login.vue')['default']
    RegForm: typeof import('./src/components/RegForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestingHello: typeof import('./src/components/TestingHello.vue')['default']
    UserRegistration: typeof import('./src/components/UserRegistration.vue')['default']
  }
}
